Vagrant.configure("2") do |config|
  config.vm.provision "shell", inline: "echo Hello"

  config.vm.box = "debian/buster64"
  config.vm.hostname = "test-target-vm"

  config.vm.provider :libvirt do |domain|
      domain.uri = 'qemu:///system'
  end

#  config.vm.provision "file", source: "../babysitter-server-prototype.key.pub", destination: "~/"
  config.vm.provision "shell", inline: <<-SHELL
    apt install tmux -y
SHELL

# Custom key not needed
#  config.vm.provision "shell", inline: <<-SHELL
#    cat ~/babysitter-server-prototype.key.pub >> /home/vagrant/.ssh/authorized_keys
#SHELL


   # See bug https://github.com/nre-learning/antidote-selfmedicate/issues/55
   # config.vm.provision "file", source: "scripts", destination: "$HOME/scripts"
   config.vm.synced_folder "scripts", "/home/vagrant/scripts", type: "rsync"


config.trigger.after [:up, :provision] do |trigger|
  trigger.info = "Running ./update-babysitter-server-ssh-config.sh locally..."
  trigger.run = {path: "./update-babysitter-server-ssh-config.sh"}
end

end

